name: Push to private

on:
  push:
    branches:
      - main

jobs:
  push-to-private:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkout other repo
        uses: actions/checkout@v4
        with:
          repository: IbraheemHaseeb7/apee-i-frontend
          token: ${{ secrets.PAT_TOKEN }}
          ref: main
          path: apee-i-frontend
          fetch-depth: 0

      - name: Push dev branch to other repo
        run : |
          cd apee-i-frontend
          num_files_updated=$(git diff --numstat | wc -l)
          echo "::notice::${num_files_updated} files were updated"
          if (( num_files_updated > 0 )); then
            git config user.name "${GITHUB_USER}"
            git config user.email "${GITHUB_EMAIL}"
            git add .
            git commit -m "this-repo triggered: Updated ${num_files_updated} files"
            git push -u origin main
          fi

