name: Push to private

on:
  push:
    branches:
      - main

jobs:
  push-to-private:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3
      with:
        repo: IbraheemHaseeb7/apee-i-frontend.git
        ref: main
        token: ${{ secrets.PAT_TOKEN }}

    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Add and Commit
      run: | 
        git add .
        git commit -m "${{ github.event.head_commit.message }}" 

    - name: Push code to Private repo
      run: |
        git push origin main --force

