name: Push to private

on:
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node JS
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install yarn
      run: npm install -g yarn

    - name: Install Deps
      run: yarn install

    - name: Run Checks
      run: yarn run lint

  push-to-private:
    runs-on: ubuntu-latest

    needs: eslint

    steps:
      - uses: actions/checkout@v4

      - name: Checkout other repo
        uses: actions/checkout@v4
        with:
          repository: IbraheemHaseeb7/apee-i-frontend
          token: ${{ secrets.PAT_TOKEN }}
          ref: main
          path: apee-i-frontend
          fetch-depth: 0

      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          repository: apee-i/landing
          token: ${{ secrets.PAT_TOKEN }}
          ref: main
          path: landing
          fetch-depth: 0

      - name: Push dev branch to other repo
        run : |
          rm -rf landing/.git
          mv apee-i-frontend/.git landing
          cd landing

          num_files_updated=$(git diff --numstat | wc -l)
          echo "::notice::${num_files_updated} files were updated"
          if (( num_files_updated > 0 )); then
            git checkout -b master
            git config --local user.name "IbraheemHaseeb7"
            git config --local user.email "ibraheemhaseeb7@gmail.com"
            git add .
            git commit -m "this-repo triggered: Updated ${num_files_updated} files"
            git push -u origin master --force
          fi

